import type { AuctionItem } from '@/types/auction'

export const mockAuctions: AuctionItem[] = [
  {
    id: '1',
    title: 'Rare Digital Artwork NFT',
    description: 'A unique piece from renowned crypto artist. Your bid remains completely confidential until auction ends.',
    imageUrl: 'https://images.unsplash.com/photo-1634986666676-ec8fd927c23d?w=800&auto=format&fit=crop',
    startingBid: 0.5,
    currentHighestBid: null,
    encryptedBidsCount: 7,
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    status: 'active',
    category: 'Art',
  },
  {
    id: '2',
    title: 'Exclusive Web3 Domain',
    description: 'Premium .eth domain with massive potential. All bids encrypted via FHEVM.',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop',
    startingBid: 1.0,
    currentHighestBid: null,
    encryptedBidsCount: 12,
    startTime: new Date(Date.now() - 1 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    status: 'active',
    category: 'Domains',
  },
  {
    id: '3',
    title: 'Genesis Collection NFT',
    description: 'First edition from the legendary collection. Privacy-preserving bids powered by Zama.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop',
    startingBid: 2.5,
    currentHighestBid: null,
    encryptedBidsCount: 23,
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 1 * 60 * 60 * 1000),
    status: 'active',
    category: 'Collectibles',
  },
  {
    id: '4',
    title: 'Virtual Real Estate Plot',
    description: 'Prime location in the metaverse. Secure your bid with homomorphic encryption.',
    imageUrl: 'https://images.unsplash.com/photo-1634973357973-f2ed2657db3c?w=800&auto=format&fit=crop',
    startingBid: 5.0,
    currentHighestBid: null,
    encryptedBidsCount: 5,
    startTime: new Date(Date.now() + 1 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
    status: 'upcoming',
    category: 'Real Estate',
  },
  {
    id: '5',
    title: 'AI-Generated Masterpiece',
    description: 'Stunning AI art piece with verified provenance. Nobody knows the current highest bid!',
    imageUrl: 'https://images.unsplash.com/photo-1635322966219-b75ed372eb01?w=800&auto=format&fit=crop',
    startingBid: 0.8,
    currentHighestBid: null,
    encryptedBidsCount: 15,
    startTime: new Date(Date.now() - 4 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 3 * 60 * 60 * 1000),
    status: 'active',
    category: 'Art',
  },
  {
    id: '6',
    title: 'Legendary Gaming Asset',
    description: 'Ultra-rare in-game item from popular blockchain game. Your bid stays secret.',
    imageUrl: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&auto=format&fit=crop',
    startingBid: 1.5,
    currentHighestBid: null,
    encryptedBidsCount: 31,
    startTime: new Date(Date.now() - 5 * 60 * 60 * 1000),
    endTime: new Date(Date.now() + 30 * 60 * 1000),
    status: 'active',
    category: 'Gaming',
  },
]
